100% width for form items
osu-wams/madrone pull request #115
Opened 2022-07-18 19:28 UTC by mechanoid23

2022-07-18 21:03 UTC, Ruefa requested changes

2022-07-18 21:03 UTC, Ruefa commented on src/scss/_osu_layout_builder.scss
> +    //width: initial !important;
Do we need to keep this comment?

2022-07-18 22:00 UTC, mechanoid23 commented on src/scss/_osu_layout_builder.scss
> +    //width: initial !important;
Thanks for catching that!

2022-07-19 00:04 UTC, emerham commented
Can we also add a fix specifically to address the radios?
![Screenshot from 2022-07-18 16-57-27](https://user-images.githubusercontent.com/9220641/179636550-c14ba8eb-2562-4e95-9ed1-b7c371dd1bdc.png)

```css
#drupal-off-canvas .form-radios > div,
#layout-builder-modal .form-radios > div {
  width: initial;
}
```

![Screenshot from 2022-07-18 17-04-16](https://user-images.githubusercontent.com/9220641/179636854-d2f3551b-6980-4a07-ab50-44685190f6ae.png)

2022-07-19 00:05 UTC, emerham requested changes
comment above about radios.

2022-07-19 17:51 UTC, Ruefa approved these changes

2022-07-19 17:56 UTC, emerham approved these changes
LGTM

2022-07-19 19:16 UTC, merged