DRUP8-1002 Hide main menu when on a group page
osu-wams/madrone pull request #89
Opened 2022-04-26 21:23 UTC by Ruefa

2022-04-28 18:58 UTC, emerham requested changes
Some minor changes and then we should be good

2022-04-28 18:58 UTC, emerham commented on templates/block/block--superfish--main.html.twig
> +      {{ is_group_page }}
Is this still needed?

2022-04-28 18:58 UTC, emerham commented on madrone.theme
> + */
Add documentation for the return type. something like
```/**
 * Helper function to check if current page is associated with a group.
 *
 * @return bool
 *   True if current page is in a group and false if not.
 */
```

2022-04-28 18:58 UTC, emerham commented on templates/block/block--superfish--main.html.twig
> +      {{ is_group_page }}
specifically the {{ is_group_page}}

2022-04-29 18:20 UTC, Ruefa commented on templates/block/block--superfish--main.html.twig
> +      {{ is_group_page }}
Good catch that was just for debugging

2022-04-29 18:22 UTC, emerham approved these changes
That looks great! thanks for the updates.

2022-04-29 18:32 UTC, merged